### PR TITLE
support scaling from the top and make scale factor configurable

### PR DESCRIPTION
**Pull request by EyMaddis**
This change allows you to change the origin of the scaling to the top of the view.
In combination with setting the new property `backgroundScale={2}` the following effect:

result
[Source](https://codentrick.com/parallax-effect-for-ios-with-swift-part-2/)

I would have liked to change the default value of `backgroundScale` to 2, but it would not be API compatible.

### CODE REVIEW

**Comment by z4o4z** [comment]
Hi @EyMaddis , thanks for this cool PR! Can you add an example(storybook story) which will demonstrate this feature?

**Comment by z4o4z** [comment]
Hi @EyMaddis, I've just added this feature to the 1.7.0 version. Thanks a lot!

**Comment by EyMaddis** [comment]
@z4o4z Whoop whoop. 
Time is short right now, maybe I will open a storybook PR in the future.

Thanks for merging.

**Comment by z4o4z** [comment]
@EyMaddis no worry, I already added the examples. Maybe do you have some ideas for improving this lib?

**Pull request merged**
